### ISSUE TITLE
Rate limiting updates

### ISSUE THREAD

**Issue by Watchful1** [praw-dev/prawcore#143]
### Describe the solution you'd like

I updated the rate limiting code a couple years ago in #89, but reddit's recent changes have exposed some limitations in the algorithm.

When the requests per window is very low, like reddit's new unauthenticated limit of 10 requests per minute, the algorithm waits its default maximum of 10 seconds between requests until it "catches up". And when the requests per window is high, like the new rate limit of 100 per minute, it runs through requests as quickly as possible and then abruptly slows down once it again catches up. In both cases it should ideally use requests at a steady rate the through the whole window.

I made several attempts at a new algorithm and was going to have a spreadsheet demonstrating the improvements like I did last time I brought this up, but I ended up not being satisfied with anything I came up with. Fixing the problems above is compounded by the issues I fixed last time, starting requests in the middle of a reset window and there being multiple clients making requests at the same time.

So I wanted to bring up an idea before I put more time into it. The current approach only uses the values from the previous request. @bboe what would you think of keeping more state, a running average using a couple recent requests to help estimate how many requests per second are being used and how long to wait.

If you don't think that's a terrible idea I can mock something up for you to take a look at.

**Comment by bboe** [comment]
>  @bboe what would you think of keeping more state, a running average using a couple recent requests to help estimate how many requests per second are being used and how long to wait.

I'm fine with whatever approach you think will work best. What you've described seems to make sense. My only suggestion is that I would recommend optimizing for the 100 requests/minute users over the 10 requests/minute ones.

**Comment by Watchful1** [comment]
I've put together a new algorithm. Turns out the important number to know is the size of the reset window. So in the implementation I'll calculate and store the largest reset time - current time. Alternatively I could just assume it's 600 seconds, which has been true for the last 10+ years, but I'm not sure it's worth depending on it. If the reset window is ever substantially longer than our assumption, the algorithm breaks down and sleeps a long time after the first request.

Here's a spreadsheet for you to take a look. The current version is on the left and the new one is on the right. There's also graphs on the far right comparing the two if you scroll over far enough. You can make a copy of the spreadsheet to edit the constants at the top.

https://docs.google.com/spreadsheets/d/1sxmqTzm7uPhG9klqzbrJb69HzXaN45Wl-PdfT8JKOaQ/edit#gid=387468893

**Comment by bboe** [comment]
I took a brief glance at the graphs, and I think having a consistent delay is reasonable. I like the idea of dynamically supporting larger reset windows, in the off-chance Reddit changes it rather than assuming 600.

I'll admit, I liked that what I once implemented allowed for bustiness at the beginning of a window rather than being strictly linear. However, that certainly came with complexities, and I think it didn't play nicely to multiple scripts with the same credentials hence why you did the initial re-write.

At the end of the day, as long as the code is well written, we're going to accept your PR. Thanks for looking into it.

**Comment by Watchful1** [comment]
Created the pull request. I had to add in some logic to estimate the max window size if you come into the window in the middle for the first time, but have already used a bunch of requests. Otherwise it sets the window size too small since it doesn't know the actual max and ends up sleeping because it thinks you're way behind.

This does allow bursting when it calculates you're "ahead" of the expected average usage over a window. Which, with reddit's new 1000 requests per second second window rate limit is basically all the time. With an average request/response time you actually can't send all 1000 requests sequentially in 600 seconds and it never sleeps at all. Even for cases where you have fewer requests, it still doesn't sleep until it thinks you've caught up with your expected average use rate.

**Comment by Watchful1** [comment]
After using my implementation for a week or so I've run into some problems. The size of the reset window is very important for the calculation and it's hard to accurately estimate until that instance of the PRAW object has gone over the window boundary. It's not a problem for long running scripts that regularly run for hours or days before being restarted, but anything short lived ends up with an inaccurate window size and either runs too fast or sleeps really long for the first few requests.

A good example would be a developer testing something, starting up a script that makes a dozen requests, then stopping it, tweaking some code and running again. After a few minutes of this the script would have burned through hundreds of requests and when it starts would see a window size of say, half the normal 10 minutes. It would then try to evenly spread the hundreds of requests it's used plus the hundreds of requests remaining across that window, assume it's far behind since its used hundreds of requests and is only, in its view, a few seconds into its window, and sleep aggressively to slow down.

As I mentioned I tried to guess at the actual window size in those cases by adding the number of requests used to the seconds remaining, but there's other drawbacks like ending up with a too large window size.

I'm going to go ahead and change it to a default window size of 600 seconds, which handles these cases much better. I think it's not worth the issues for the off chance reddit actually changes the window size in the future. I'll put in a config parameter so it can easily be changed, not sure if that requires a change to praw too.

**Comment by bboe** [comment]
Sounds good. Thanks for reporting back.

**Comment by Watchful1** [comment]
@bboe I opened #147 with a default. If that looks good I'll get to work on the PRAW side merge request.

**Comment by casrar** [comment]
Any updates on this? Has it been fixed?

**Comment by Watchful1** [comment]
The code is merged, but there are some changes that need to be made over on the PRAW side before a new version is released.

You should be able to install the dev version by doing `pip uninstall prawcore` and then `pip install -e git+https://github.com/praw-dev/prawcore#egg=prawcore`

**Comment by casrar** [comment]
Ahh gotcha cool! If there's anything that still needs investigated I'm more than willing to sink some time in. Might just need someone to bring me up to speed on it if that's the case.

**Comment by LilSpazJoekp** [comment]
Can we close this?
