### ISSUE TITLE
Add public settings for changing the number of retries

### ISSUE THREAD

**Issue by dequeued0** [praw-dev/prawcore#87]
Please add public settings for changing the number of retries (e.g., an environment variable and Python variable similar to `prawcore_timeout` and `prawcore.requestor.TIMEOUT`).

`reddit._core._retry_strategy_class._retries = N` is the only way to change it right now.

Thanks!

**Comment by bboe** [comment]
@dequeued0 would you like to make such a PR?

**Comment by bboe** [comment]
I'm going to close this issue as it's been over a year and no one has made a PR.
