### ISSUE TITLE
Rate limiting is overly conservative

### ISSUE THREAD

**Issue by Watchful1** [praw-dev/prawcore#89]
Currently the sleep time between requests is calculated based purely on the requests remaining and the seconds to reset, and doesn't take into account the time it takes for the request itself.

As an example, my tests are averaging 0.65 seconds for the request itself to return. So right after the reset, with 600 requests and 600 seconds, praw will wait 1 second, then the request takes 0.65 seconds. If I hit the middle of the window, say 600 requests left and 300 seconds, it will wait 0.5 seconds, then the request takes 0.65 seconds, which still results in a total wait time of 1.15 seconds.

So in 600 seconds you end up sending something like 350-400 requests.

I think this should be changed to have no sleep time at all if the number of requests remaining is greater than the number of seconds until reset. Or possibly a bit of buffer, if the requests remaining is, say, more than 10 above the number of seconds until reset. Just to make sure there's no edge case where you end up waiting 10 seconds for something.

**Comment by Watchful1** [comment]
I did some math and here's my proposed formula

`max(min((seconds_to_rest - cur_remaining) / 2, 10), 0)`

as opposed to the current formula

`(min(prev_remaining - cur_remaining, 1) * seconds_to_reset) / cur_remaining`

There's no need to keep track of the previous remaining requests, the new formula quickly approaches the actual number of requests used per second without it. I put together a [spreadsheet](https://docs.google.com/spreadsheets/d/1sxmqTzm7uPhG9klqzbrJb69HzXaN45Wl-PdfT8JKOaQ/edit?usp=sharing) that illustrates the effects of the two formulas. You can make a copy of it and change the numbers at the top to see how the two options react over time.

**Comment by bboe** [comment]
The purpose of previous remaining is to try to avoid going over the rate
limit if more than one instance is running concurrently. Supporting that
unfortunately makes this a bit more complicated.

**Comment by Watchful1** [comment]
The new formula takes that into account. The spreadsheet I linked demonstrates it if you changed the requests per second field.

**Comment by bboe** [comment]
Cool, I missed that part.

**Comment by bboe** [comment]
I think there's something up with `seconds_to_reset` as it is reported in the response headers, so it shouldn't diverge from the real number of `seconds_to_reset` unless you are only making requests which don't receive that header.

**Comment by Watchful1** [comment]
The spreadsheet bases the timestamp field on the number of actual seconds, ie, sleep seconds plus round trip time for the request. Then the seconds to reset field is just `seconds to reset at the start - seconds elapsed`.

So unless I'm completely misinterpreting what the value returned in the headers is it should be accurate. As an example, if the seconds to reset is 600, then you wait 4 seconds and send a request, it would be 596 right? Then wait another 4 seconds and send another request and it would be 592. Or rather, since it's a timestamp it just doesn't change until it passes and the window resets.

The spreadsheet represents a single request per row, it would be a bit more complicated to do it as one second per row.

**Comment by bboe** [comment]
I guess what I'm not getting is why why seconds to reset 0 when the timestamp is 473.79 (row 368). Seconds to reset shouldn't be that far off from `600 - timestamp`.

**Comment by Watchful1** [comment]
Ah, I'm sorry, you're right. I had a `$` backwards in that column. It should be fixed now.

**Comment by bboe** [comment]
> As an example, if the seconds to reset is 600, then you wait 4 seconds and send a request, it would be 596 right? Then wait another 4 seconds and send another request and it would be 592.

That's correct, assuming it takes no time at all to make the request. However, since it takes time to actually make requests, the header `x-ratelimit-reset` will decrease faster than described here and thus the timestamp should closely follow `600-second_to_reset`.

**Comment by bboe** [comment]
Okay, that looks much better. I didn't account for high latency for requests and what your spreadsheet is showing is that around 200ms we stop issuing all requests available in a period.

While I see you incorporated estimated clients into the left-side of the spreadsheet, I'm not seeing that at all in the right side. Also, when there are estimated clients the number of requests remaining per each request from this client should decrease by the that number. For simplicity, I would suggest making the estimated number of clients a constant rather than a setting per row.

**Comment by Watchful1** [comment]
It's not necessary on the right side. The new formula accounts for the case where the number of requests remaining decreases faster than one per request sent. If the number of requests remaining is less than the seconds to reset, the formula automatically waits longer until it evens out. If you make a copy of the spreadsheet and change the "Requests per second" cell at the top to 2, then the "Requests remaining" decrements by 2 each line and the "Total time" from the sleep formula increases to match it.

I put the "Estimated clients" field on each row on the left to mirror how the existing code calculates the estimated clients for each request. You're right that it's effectively a constant.

The current code does handle multiple clients fairly well. If we start at 600 requests remaining and 600 seconds to reset, here's a table of how many total requests get sent in the 600 seconds (for just the current client, not counting how many are sent by other clients).

Num Clients|Current requests|New requests
-|-|-
1|472|599
2|287|300
3|199|200
4|150|150
5|120|120
6|100|100
7|86|86
8|75|75
9|67|67
10|60|60

The major improvement is if you start sending requests when it's already in the middle of the reset window. Here's a table of how many requests we get off if there are 600 requests remaining and different numbers of seconds before reset (all with 1 client, though the gains are similar with multiple).

Seconds to reset|Current requests|New requests
-|-|-
600|472|599
500|435|599
400|386|599
300|323|462
200|242|309
100|137|155

Note how with the new formula we still get off 599 requests even if there are only 400 seconds till the reset.

In and of itself this allows for a fair amount of bursting. If you have extra requests it just uses them as fast as possible. I agree it would be nice to have a way to tell praw to burst requests past that. Before I figured this out, my idea was a function to set a number of requests for praw to burst. You could pass in say, 30, and then praw would not sleep for the next 30 requests.

**Comment by bboe** [comment]
Cool. Let's put it in as the default.
